### ISSUE TITLE
ConfigureTracerProvider doesn't need a logger

### ISSUE THREAD

**Issue by joe94** [xmidt-org/candlelight#12]
All the errors getting logged could simply be returned to users of this package so they may log it if they see fit. 

https://github.com/xmidt-org/candlelight/blob/26649f5fb0827273399b2057188fb145786cac70/candlelight.go#L45

**Comment by Sachin4403** [comment]
Resolved this issue and raised a PR for the same: https://github.com/xmidt-org/candlelight/pull/15
