### ISSUE TITLE
Return TracerProvider object instead of creating globally

### ISSUE THREAD

**Issue by kristinaspring** [xmidt-org/candlelight#13]
We can return the `TraceProvider` created in `ConfigureTracerProvider()`, instead of creating a global object:
https://github.com/xmidt-org/candlelight/blob/26649f5fb0827273399b2057188fb145786cac70/candlelight.go#L45

This will better allow for tracking structs and functions with a dependency on the `TracerProvider`, because it must be passed explicitly.  Global mutable objects are generally something we want to avoid, as it can make code more brittle and cause difficult to predict/find issues in the future.

For example, to configure zipkin:
https://github.com/xmidt-org/candlelight/blob/26649f5fb0827273399b2057188fb145786cac70/candlelight.go#L55

When I looked at the docs, it looks like we can call [`NewExportPipeline()`](https://pkg.go.dev/go.opentelemetry.io/otel/exporters/trace/zipkin#NewExportPipeline) instead of `InstallNewPipeline()`.

**Comment by Sachin4403** [comment]
Resolved this issue and raised a PR for the same: https://github.com/xmidt-org/candlelight/pull/15
