### ISSUE TITLE
Modify comments to follow Effective Go guidelines

### ISSUE THREAD

**Issue by kristinaspring** [xmidt-org/candlelight#14]
Certain code comments are parsed and used for the documentation hosted on pkg.go.dev. Because of this, we want those comments to follow common Go convention and keep our documentation easy to read and understand.  Effective Go has a section on [comments](https://golang.org/doc/effective_go#commentary).  The main takeaways are:
- Comments for exported structs/functions/variables should begin with a one sentence summary that starts with the name of the struct/function/variable.
- Comments should contain complete sentences.

All the comments should be fixed to follow these guidelines, below is one of our current comments.
https://github.com/xmidt-org/candlelight/blob/26649f5fb0827273399b2057188fb145786cac70/candlelight.go#L39-L44

Here is an example of a comment that follows these guidelines:
https://go.googlesource.com/go/+/go1.16/src/net/http/fs.go#693

---

This issue is probably best worked on after fixing more functionality-specific issues, or remembering while fixing other things.

**Comment by Sachin4403** [comment]
Resolved this issue and raised a PR for the same: https://github.com/xmidt-org/candlelight/pull/15
