### ISSUE TITLE
Better name for HeaderConfig?

### ISSUE THREAD

**Issue by joe94** [xmidt-org/candlelight#18]
AFAIK, the purpose of [HeaderConfig](https://github.com/xmidt-org/candlelight/blob/a1596799d72e58f79bbfed335f18b3016eb09df9/config.go#L42) is just to provide a configurable way to name the span and trace IDs in logs and in http responses for debugging.

There might be a better name we could choose to avoid confusion in thinking this applies to the non-configurable `otel` trace headers https://github.com/open-telemetry/opentelemetry-go/blob/v0.18.0/propagation/trace_context.go#L31

**Comment by Sachin4403** [comment]
Here are my suggestions 

1. ResponseLogConfig
2. CustomConfig

if you have some other better name, please suggest.

**Comment by kristinaspring** [comment]
Do we need `HeaderConfig`? I'm starting to wonder the benefit of adding our own headers when the values are already provided in headers hardcoded into `otel`?

**Comment by Sachin4403** [comment]
This config is required if user want to add his own custom headers instead of using the defaults one.

**Comment by kristinaspring** [comment]
The initial request that provides the tracing must provide the headers hardcoded into `otel/propogation`:
https://github.com/xmidt-org/candlelight/blob/main/middleware.go#L39

These are the headers:
https://github.com/open-telemetry/opentelemetry-go/blob/v0.18.0/propagation/trace_context.go#L31-L32

We can only get tracing values if the propogation headers are set, so why set other headers?

**Comment by joe94** [comment]
Yeah, exactly. I'd just add that the OTEL propagation headers flow in the direction of the **request**:

```
[Origin] ==(non-configurable OTEL headers in request)==> [Target]
```

And HeadersConfig is actually writing back on the **response** headers. I don't think this is part of the OTEL standard either.

```
[Origin] <==(headerConfig headers in response)== [Target]
```

**Comment by Sachin4403** [comment]
Yes, it is not part of `otel`. I had added it for easier debugging if anything is wrong in any particular request then we can check in the logs based on TraceID which is available in the response headers. 

HeaderConfig is only responsible for customizing the response header name and Trace and SpanID log keys in the logger, if it is not supplied in properties then defaults will be used.

**Comment by joe94** [comment]
Gotcha. These headers will help capture the trace information that we can use for debugging a particular request. 

I think having these customizable headers is fine. Maybe we should change the defaults to something like `X-Midt-Trace-ID` instead of the existing ones which look too similar to zipkin's https://github.com/openzipkin/b3-propagation

As for logging, we usually don't make our logging keys configurable so instead of [this](https://github.com/xmidt-org/tr1d1um/pull/197/files#diff-f2f88dc0ca897c7f32c20739cc366ecb1e48d4d6625c7b0474d5b73491a85eb0R56)

```
errorLogger.Log(logging.MessageKey(), "transaction logger not found in context", "tid", tid,spanIDHeaderName, spanId,traceIDHeaderName,traceId)
```

We could just have this
```
errorLogger.Log(logging.MessageKey(), "transaction logger not found in context", "tid", tid, "span-id", spanId, "trace-id",traceId)

```

**Comment by kristinaspring** [comment]
I agree with Joel - also `"span-id"` and `"trace-id"` could be constants in this package, allowing for application code to not need to recreate these string values.

**Comment by joe94** [comment]
Oh and a better name for this struct might be something like `ResponseHeaderConfig`

```
// ResponseHeaderConfig allows configuring the HTTP response headers that will capture 
// existing OpenTelemetry tracing data. These headers can help identify a request's tracing info
// for further debugging.
type ResponseHeaderConfig struct {
	// SpanIDHeaderName is the name of the header that will capture the OpenTelemetry main span ID for this service.
	SpanIDHeaderName string `json:"spanIDHeaderName"`

	// TraceIDHeaderName is the name of the header that will capture the OpenTelemetry trace ID of the request.
	TraceIDHeaderName string `json:"traceIDHeaderName"`
}
```

**Comment by Sachin4403** [comment]
Hi @joe94 and @kristinaspring, if we are planning to use `span-id` and `trace-id` directly in logs without relying on the configuration provided by a user, we can use `X-Midt-Trace-ID` and `X-Midt-Span-ID` the same way we are using `X-Midt-Transaction-ID` then do we need `ResponseHeaderConfig` or `HeaderConfig`?

**Comment by joe94** [comment]
Yeah, that works for me. I don't really see a big use case to make these configurable for now. It'll keep things simply as well. What do you think, @kristinaspring?

**Comment by kristinaspring** [comment]
I like that solution; it makes sense and expands on conventions we already
have.
