### ISSUE TITLE
Use a Config type

### ISSUE THREAD

**Issue by johnabass** [xmidt-org/candlelight#6]
The `ConfigureTracerProvider` function currently uses `viper` directly to extract configuration.  This has certain disadvantages:

- It's not obvious what this package expects for configuration.  One would have to read the code.  Of course, `godoc` can describe the configuration options, but then the comments have to be manually kept in sync with code.
- It's tied to `viper`.  Plenty of other ways of managing configuration exist and are in common use.
- It's difficult to test.  Test code has to set up a `viper` instance with the appropriate configuration.  That test code is then brittle.  Any change to the `ConfigureTracerProvider` implementation can be modified to use new or different configuration information.  The compiler has no way of detecting that condition, so a test maintainer has to have more intimate knowledge of the code.

The best solution to the above disadvantages is to use a configuration type and remove any use of `viper`.  That is also what is in common practice for `golang` packages.

For example:

```
// Config holds the available configuration options for tracer infrastructure
type Config struct {
    // ApplicationName is the name for this application
    ApplicationName string `json:"applicationName"`

    // Provider is the name of the trace provider to use
    Provider string `json:"provider"`

    // as many fields as desired ...
}

func ConfigureTracerProvider(cfg Config) error {
    // now, rather than extracting fields from viper, just use the appropriate fields from Config
}
```

Clients can then create or unmarshal a `Config` object using `viper`, `encoding/json`, a global variable, or whatever is suitable to their needs.  The `candlelight` library need not concern itself with how the `Config` object gets created.

**Comment by Sachin4403** [comment]
Resolved this issue and raised a PR for the same: https://github.com/xmidt-org/candlelight/pull/15
