### ISSUE TITLE
Table-driven tests

### ISSUE THREAD

**Issue by johnabass** [xmidt-org/candlelight#8]
In `candlelight_test.go`, there are unit tests which only differ based upon input.  The underlying production code logic may be the same, but the tests have a lot of repeated code.  This is exactly the situation that the table-driven test pattern is aimed at addressing.

For reference: https://dave.cheney.net/2013/06/09/writing-table-driven-tests-in-go

The following example assumes that https://github.com/xmidt-org/candlelight/issues/6 has been implemented:

```
func TestConfigureProvider(t *testing.T) {
    testData := []struct{
        cfg Config
        expectedError error // can be nil to indicate no error
    }{
        // one "record" per test
        {
            cfg: Config{
                Provider: "jaeger",
            }, // expectedError is left nil
        },
        {
            cfg: Config{
                Provider: "someValueThatWillForceAnError",
            },
            expectedError: errors.New("this might be a global ErrXXX variable in the package"),
        },
    }

    for i, record := range testData {
        t.Run(strconv.Itoa(i), func(t *testing.T) {
            assert := assert.New(t) // notice that this assert is not global ...
            assert.Equal(
                record.expectedError,
                ConfigureProvider(record.cfg),
            )
        })
    }
}
```

In the above, each record is run in a separate subtest via `t.Run`.  This isn't strictly necessary, but it does help organize the test output.  It's much easier to debug test breaks when each `testData` record is run in a separate subtest whose name is something you can use to track down which piece of test data caused the failure.  I've used the 0-based index here for that purpose.

**Comment by Sachin4403** [comment]
Resolved this issue and raised a PR for the same: https://github.com/xmidt-org/candlelight/pull/15
