### ISSUE TITLE
Test data and coverage

### ISSUE THREAD

**Issue by johnabass** [xmidt-org/candlelight#9]
`ConfigureTracerProvider` contains a `switch/case` statement with 2 cases and a default.  The tests are written with knowledge of that implementation.  This does give high code coverage, but it misses several nuances.

Unit tests are better implemented from a client's perspective.  Clients don't know how `ConfigureTracerProvider` is implemented.  So a client may pass any of the following values for the provider name:

- A known, supported value, e.g. "jaeger"
- A mixed case value, e.g. "JaeGeR".  This only applies if your configuration is case-insensitive.
- An empty string
- An unset field.  This is often handled implicitly by testing an empty string, but not always.
- An unsupported string that contains valid characters.  What is considered "valid" will be specific to the code under test (see next).
- A string with junk characters.  What "junk" means is specific to the code under test.  For example: if your code doesn't support a `#` character, then make sure there's at least (1) negative test case with a string containing `#`.

Some of the above cases might not apply here.  I'm not sure what `opentelemetry` allows for provider names.

Several of the above values will be handled by the same `case`.  But tests shouldn't be written with that knowledge.  You don't know how `ConfigureTracerProvider`'s implementation will change in the future.

**Comment by Sachin4403** [comment]
Resolved this issue and raised a PR for the same: https://github.com/xmidt-org/candlelight/pull/15
